version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - /data/docker/volumes/qdrant_storage:/qdrant/storage
    restart: always
    environment:
      QDRANT__SERVICE__GRPC_ENABLE: "true"

