version: '3.9'

volumes:
  db_storage:
  n8n_storage:
  redis_data:
  qdrant_data:

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=n8n
      - TZ=Asia/Bangkok  # ✅ เพิ่ม timezone สำหรับ PostgreSQL
    volumes:
      - db_storage:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro  # ✅ mount timezone file
      - /etc/localtime:/etc/localtime:ro  # ✅ mount localtime file
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d n8n"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: my_redis
    environment:
      - TZ=Asia/Bangkok  # ✅ เพิ่ม timezone สำหรับ Redis
    volumes:
      - redis_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6381:6379"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: my_qdrant
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      TZ: Asia/Bangkok  # ✅ เพิ่ม timezone สำหรับ Qdrant
    volumes:
      - qdrant_data:/qdrant/storage
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6333:6333"

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=admin
      - DB_POSTGRESDB_PASSWORD=P@ssw0rd
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PORT=5678
      - NODE_ENV=production
      - N8N_HOST=localhost
      - N8N_SECURE_COOKIE=false
      - TZ=Asia/Bangkok  # ✅ เพิ่ม timezone สำหรับ N8N
      - GENERIC_TIMEZONE=Asia/Bangkok  # ✅ N8N specific timezone setting
    ports:
      - "5679:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
      - /etc/timezone:/etc/timezone:ro  # ✅ mount timezone file
      - /etc/localtime:/etc/localtime:ro  # ✅ mount localtime file
    depends_on:
      postgres:
        condition: service_healthy
